### PR TITLE
Add support for custom date format

### LINKED ISSUE #60: Add option for customizing date format
I would really like to see an option to customize the date format that is in the status content.

### PR DESCRIPTION
**Pull request by andersevenrud**
Adds the option "@nord_tmux_date_format" that allows for customizing the date format shown in the status content.

* Closes: #60
* Related: #24

### CODE REVIEW

**Comment by arcticicestudio** [comment]
Hi @andersevenrud :wave:, thanks for your contribution :+1:
I'll try to test and review the changes this weekend.

**Comment by andersevenrud** [comment]
Great, thanks! :)

**Review by svengreb — APPROVED** [review]

**Review by arcticicestudio — APPROVED** [review]
LGTM 👍🏼 
For the next [Nord documentation][1] update this will be added, including the still missing time format option.

[1]: https://github.com/arcticicestudio/nord-docs

**Comment by andersevenrud** [comment]
Neat :) Thanks for looking into this so quickly.

**Pull request merged**
